repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        name: end-of-file-fixer
        exclude: pgdoc_datatype_parser/pg-releases\.json
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.3.0
    hooks:
      - id: setup-cfg-fmt
        args:
          - --include-version-classifiers
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print
          - flake8-implicit-str-concat
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --filter-files
        files: \.py$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        files: .+\.(yml|yaml)
        args:
          - -c
          - .yamllint
  - repo: https://github.com/mondeja/pre-commit-hooks
    rev: v1.8.0
    hooks:
      - id: root-editorconfig-required
      - id: dev-extras-required
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.2
    hooks:
      - id: editorconfig-checker
